In [5]:
import numpy as np
import math

#Creating random matrix subroutines
def rand_not_diag(n):
    m = np.matrix(np.random.randn(n, n))*n*100
    return np.dot(m.transpose(), m)

def rand_diag(n):
    m = np.matrix(np.random.randn(n, n))*n*100
    for i in range(n):
        m[i, i] = np.sum(np.abs(m[i]))
    return m  

#Estimation subroutine
def apr(a, b, pres):
    q = np.linalg.norm((a - np.diag(np.diagonal(a))) / np.matrix(np.diagonal(a)).transpose(), np.inf)
    return int(math.log(pres/np.linalg.norm(b), q)) + 1, q

#Solving
def jacobi(a, b, pres=1e-12):
    max_iter, q = apr(a, b, pres)
    x = np.matrix(np.zeros_like(b, dtype=np.double))
    t = a - np.diag(np.diagonal(a))
    iters = 0
    for i in range(max_iter):
        iters += 1
        x_  = x.copy()
        x = (b - t*x) / np.matrix(np.diagonal(a)).transpose()
        if q * np.linalg.norm(x - x_, np.inf) / (1 - q) < pres:
            break
    return x, iters


def seidel(a, b, pres=1e-12):
    max_iter, q = apr(a, b, pres)
    x = np.matrix(np.zeros_like(b, dtype=np.double))
    iters = 0
    for k in range(max_iter):
        iters += 1
        x_  = x.copy()
        for i in range(A.shape[0]):
            x[i] = (b[i] - np.dot(a[i,:i], x[:i]) - np.dot(a[i,(i+1):], x_[(i+1):])) / a[i ,i]
        if q * np.linalg.norm(x - x_, np.inf) / (1 - q) < pres:
            break
    return x, iters

In [8]:
#create random n*n matrix A
N = np.random.randint(3, 5)
A = rand_diag(N)
print("matrix A: ")
print(A)

#test 0 (jacobi)
print("\n", "Jacobi: ")
B = np.matrix(np.random.randn(N, 1))*N*100
print("matrix b: ")
print(B)

X, Jsteps = jacobi(A, B)
print("\n\n", "Steps:")
print(Jsteps)
print("\n", "b - A*x")
print(B - A*X)

#test 1 (seidel)
print("\n\n", "Seidel: ")
B = np.matrix(np.random.randn(N, 1))*N*100
print("matrix b: ")
print(B)
X, Ssteps = seidel(A, B)
print("\n", "Steps:")
print(Ssteps)
print("\n", "b - A*x")
print(B - A*X)

matrix A: 
[[ 271.78769345  -85.67416125  149.96205688]
 [ 138.69764489  605.66633208  258.70566624]
 [-263.58593917 -162.90986451  501.96228469]]

 Jacobi: 
matrix b: 
[[284.97547018]
 [329.59841443]
 [383.50255251]]


 Steps:
88

 b - A*x
[[-2.58069122e-11]
 [-3.80282472e-11]
 [-5.22959454e-12]]


 Seidel: 
matrix b: 
[[-196.70117147]
 [-172.47821588]
 [-107.87764529]]

 Steps:
24

 b - A*x
[[-4.94537744e-12]
 [-4.74642547e-12]
 [ 1.42108547e-14]]
