In [1]:
import numpy as np

def GivensRotation(a):
    Rows, Cols = np.shape(a)
    q = np.identity(Rows)
    r = np.copy(a)
    rows, cols = np.tril_indices(Rows, -1, Cols)
    for (row, col) in zip(rows, cols):
        if r[row, col] != 0:
            r1 = np.hypot(r[col, col], r[row, col])
            cos = r[col, col] / r1
            sin = -r[row, col] / r1
            G = np.identity(Rows)
            G[[col, row], [col, row]] = cos
            G[row, col] = sin
            G[col, row] = -sin
            r = np.dot(G, r)
            q = np.dot(q, G.T)
    return q, r

def reverceSub(q, r, Y):
    dim = r.shape[0]
    X = np.matrix(np.zeros(shape=(dim, 1)))
    Y = np.dot(q.transpose(), Y)
    for i in range(dim):
        summ = 0
        for j in range(i):
            summ += r[dim - 1 - i, dim - 1 - j] * X[dim - 1 - j, 0]
        X[dim - 1 - i, 0] = (Y[dim - 1 - i, 0] - summ) / r[dim - 1 - i, dim - 1 - i]
    return X

In [2]:
#create random n*n matrix A
n = np.random.randint(3, 6)
A = np.matrix(np.random.randn(n, n))*n*100
print("matrix A: ")
print(A)

#test 0
Q, R = GivensRotation(A)
print("\n", "Q: ")
print(Q)
print("\n", "Q*Q.transpose(): ")
print(np.dot(Q, Q.transpose()))
print("\n", "R: ")
print(R)
print("\n", "A - Q*R: ")
print(A - np.dot(Q,R))

#test 1 (solving)
b = np.matrix(np.random.randn(n, 1))*n*100
x = reverceSub(Q, R, b)
print("\n", "A*x - b: ")
print(np.dot(A,x) - b)

matrix A: 
[[ 131.99749532 -241.65926189 -135.68941223]
 [ 537.53351833  360.75391446  185.81368817]
 [ 115.79898109   34.70400728  -91.13953471]]

 Q: 
[[ 0.23342288 -0.96403734 -0.12706596]
 [ 0.95056819  0.25375101 -0.17897076]
 [ 0.20477761 -0.07900899  0.97561453]]

 Q*Q.transpose(): 
[[ 1.00000000e+00 -1.16386640e-16 -4.20324142e-18]
 [-1.16386640e-16  1.00000000e+00 -3.72928182e-17]
 [-4.20324142e-18 -3.72928182e-17  1.00000000e+00]]

 R: 
[[ 5.65486539e+02  2.93619000e+02  1.26292233e+02]
 [ 5.70682348e-15  3.21768296e+02  1.85160916e+02]
 [-6.24627378e-15  1.20791837e-15 -1.04930765e+02]]

 A - Q*R: 
[[2.84217094e-14 5.68434189e-14 5.68434189e-14]
 [1.13686838e-13 0.00000000e+00 2.84217094e-14]
 [1.42108547e-14 2.13162821e-14 0.00000000e+00]]

 A*x - b: 
[[-5.68434189e-14]
 [ 0.00000000e+00]
 [-2.84217094e-14]]
